// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const formContainer: string;
export const inputBox: string;
export const messageInput: string;
