// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const followAndSubscribeBlock: string;
export const follow: string;
export const followLink: string;
export const subscribe: string;
export const subscribeGroup: string;
