// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const aboutBlock: string;
export const aboutBlockContent: string;
export const aboutText: string;
export const postButton: string;
export const arrowIcon: string;