// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const bottomNewsGrid: string;
export const bottomNewsGridWrapper: string;
export const bottomNews: string;
export const bottomNewsContent: string;
export const bottomNewsMeta: string;
export const entryP: string;
export const entryButton: string;
export const entryIcon: string;
export const thumbnailImg: string;