// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const box: string;
export const product_single: string;
export const product_image: string;
export const product_deatils: string;
export const product_button: string;
export const product_title: string;
