// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const detail_title: string;
export const box: string;
export const product_image: string;
export const information: string;
export const list: string;
export const actionBox: string;
export const project_information_box: string;
