// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const box: string;
export const contact: string;
export const location_single: string;
export const contact_single: string;
export const contact_icon: string;
export const input_box: string;
export const google_map: string;
