// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const newsBoxContainer: string;
export const mainNews: string;
export const newsTextContainer: string;
export const newsImg: string;
export const softNews: string;
export const softNewsImg: string;
export const newsTextContent: string;
export const aDate: string;
export const leftBox: string;
export const rightBox: string;