// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const postHeader: string;
export const postDate: string;
export const adminLink: string;
export const mainImg: string;
export const postImg: string;
export const entryContent: string;
export const initialCap: string;
export const shareList: string;
export const socialNetworksContent: string;
export const socialNetworks: string;
export const socialLink: string;
