// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const aboutMeHeader: string;
export const siteContainer: string;
export const postContainer: string;
