// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const siteContainer: string;
export const slider: string;
export const topGridNews: string;
export const newsContainer: string;
export const leftColumn: string;
export const newsSmartBox: string;
export const doubleSmartBox: string;
export const paginationContent: string;
export const sideBar: string;
export const sideBarBlock: string;
