// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const consultationBody: string;
export const quoteHeader: string;
export const consultationContent: string;
export const consultationImage: string;
export const leftImage: string;
export const rightImage: string;
export const consultationText: string;
export const subLi: string;
export const bulletList: string;
export const consultationFooter: string;
export const subP: string;
