// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const page_header: string;
export const page_container: string;
export const main_logo: string;
export const site_header: string;
export const topbar: string;
export const container_box: string;
export const topbar_content: string;
export const logo_box: string;
export const topbar_nav_box: string;
export const main_nav_header: string;
export const main_nav_box: string;
export const current: string;
export const currentMenuItem: string;
export const topbar_right_box: string;
export const main_nav: string;
export const artDirected: string;
