// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const sliderWrapper: string;
export const slide: string;
export const slideContent: string;
export const slideParagraph: string;
export const slideLink: string;
export const slideButton: string;
export const slide1: string;
export const slide2: string;
export const slide3: string;
export const activeSlide: string;
export const slideBg: string;
export const radioButtons: string;
export const radioButton: string;
export const activeRadio: string;
