// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const customPostsBlock: string;
export const customPost: string;
export const customPostContent: string;
export const customPostTextContent: string;
export const customPostDate: string;
export const aDate: string;
export const leftBox: string;
export const rightBox: string;
