// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const box: string;
export const bgImage: string;
export const widgetTitle: string;
export const widgetContactBox: string;
export const widgetContact: string;
export const widgetLinks: string;
export const widgetSocial: string;
export const hover: string;
export const bottomBox: string;
export const copyright: string;
export const hypersoft: string;
export const widgetColumn: string;
