import { ExecSyncOptionsWithStringEncoding } from "child_process";

// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const footer: string;
export const footerContent: string;
export const footerHeader: string;
export const emailContainer: string;
export const inputBox: string;
export const emailImg: string;
export const emailInput: string;
export const emailButton: string;
export const socialNetworksContent: string;
export const socialNetworks: string;
export const socialLink: string;
export const greyLink: string;
export const pinkLink: string;
export const copyright: string;