// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const page: string;
export const paginationNews: string;
export const quote: string;
export const quoteText: string;
export const quoteAuthor: string;
export const linkPost: string;
export const linkPostContent: string;
export const imagePost: string;
export const imageHover: string;
export const newsDate: string;
export const aDate: string;
export const newsButton: string;
export const arrowIcon: string;
export const pagination: string;
export const paginator: string;
export const pageButton: string;
export const currentPage: string;
export const leftNews: string;
export const rightNews: string;
export const tempHidden: string;

declare module "*.json" {
  const value: any;
  export default value;
}
