// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const siteContainer: string;
export const standartPostContainer: string;
export const postAuthorBio: string;
export const blogPostHeader: string;
