// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const doubleSmartBoxContent: string;
export const doubleSmartBoxImg: string;
export const doubleSmartBoxText: string;
export const postDate: string;
export const entryP: string;
export const postButton: string;
export const arrowIcon: string;