// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const box: string;
export const table: string;
export const tdTitle: string;
export const tdPrice: string;
