// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const post: string;
export const postContent: string;
export const postMeta: string;
export const entryP: string;
export const entryButton: string;
export const entryIcon: string;
export const postImg: string;